server:
  port: ${IEXEC_WORKER_PORT:18091}

core:
  address: ${IEXEC_CORE_ADDRESS:http://localhost:18090}

worker:
  name: ${IEXEC_WORKER_NAME:customWorker}
  volumeName: ${IEXEC_WORKER_VOLUME_NAME:iexec-worker-volume}
  localPath: ${IEXEC_WORKER_LOCAL_PATH:/home/james/iexec2}