server:
  port: ${IEXEC_WORKER_PORT:18091}

core:
  host: ${IEXEC_CORE_HOST:localhost}
  port: ${IEXEC_CORE_PORT:18090}

worker:
  name: ${IEXEC_WORKER_NAME:customWorker}
  resultBaseDir: ${IEXEC_WORKER_RESULT_BASE_DIR:/tmp/iexec-worker/}