server:
  port: ${IEXEC_WORKER_PORT:18091}

core:
  address: ${IEXEC_CORE_ADDRESS:http://localhost:18090}

worker:
  name: ${IEXEC_WORKER_NAME:customWorker}
  resultBaseDir: ${IEXEC_WORKER_RESULT_BASE_DIR:/tmp/iexec-worker-result}