server:
  port: ${IEXEC_WORKER_PORT:18091}

core:
  protocol: ${IEXEC_CORE_PROTOCOL:http}
  host: ${IEXEC_CORE_HOST:localhost}
  port: ${IEXEC_CORE_PORT:18090}

worker:
  name: ${IEXEC_WORKER_NAME:worker}
  workerBaseDir: ${IEXEC_WORKER_BASE_DIR:/tmp/iexec-worker}
  gpuEnabled: ${IEXEC_WORKER_GPU_ENABLED:false}
  gasPriceMultiplier: ${IEXEC_GAS_PRICE_MULTIPLIER:1.3} # txs will be send with networkGasPrice*gasPriceMultiplier, 4.0 means super fast
  gasPriceCap: ${IEXEC_GAS_PRICE_CAP:22000000000} #in Wei, will be used for txs if networkGasPrice*gasPriceMultiplier > gasPriceCap
  overrideBlockchainNodeAddress: ${IEXEC_WORKER_OVERRIDE_BLOCKCHAIN_NODE_ADDRESS:} #will use it if set, else will use the one given by the core
  developerLoggerEnabled: ${IEXEC_DEVELOPER_LOGGER_ENABLED:false}

wallet:
  encryptedFilePath: ${IEXEC_WORKER_WALLET_PATH:./src/main/resources/wallet/encrypted-wallet_worker1.json}
  password: ${IEXEC_WORKER_WALLET_PASSWORD:whatever}

scone:
  las:
    image: ${IEXEC_LAS_IMAGE:iexechub/sconecuratedimages-iexec}
    version: ${IEXEC_LAS_VERSION:las-v3.0}
    port: ${IEXEC_LAS_PORT:18766}
    dockerNetworkName: ${IEXEC_LAS_DOCKER_NETWORK_NAME:iexec-worker-net}

# TODO remove this
decryptFilePath: ${IEXEC_DECRYPT_FILE_PATH:./src/main/resources/decrypt-dataset.sh}
encryptFilePath: ${IEXEC_ENCRYPT_FILE_PATH:./src/main/resources/encrypt-result.sh}

management:
  endpoint:
    restart:
      enabled: true

graylog:
  host: ${IEXEC_CORE_GRAYLOG_HOST:localhost}
  port: ${IEXEC_CORE_GRAYLOG_PORT:12201}

debug:
  forceTeeDisabled: ${IEXEC_DEBUG_FORCE_TEE_DISABLED:false} # this for dev mode only
